import React, { useState, useEffect } from 'react';
import api from '../api';
import { BookOpen, Plus, Trash2, TrendingUp, Award, RefreshCw, Layers, Settings } from 'lucide-react';
import { motion } from 'framer-motion';

const gradePoints = {
    'A': 4.0, 'A-': 3.7,
    'B+': 3.3, 'B': 3.0, 'B-': 2.7,
    'C+': 2.3, 'C': 2.0, 'C-': 1.7,
    'D+': 1.3, 'D': 1.0, 'F': 0.0
};

const Courses = () => {
    const [courses, setCourses] = useState([]);
    const [userData, setUserData] = useState(null);
    const [isAdding, setIsAdding] = useState(false);
    const [isSyncing, setIsSyncing] = useState(false);
    const [syncStatus, setSyncStatus] = useState(null);
    const [newCourse, setNewCourse] = useState({ name: '', code: '', grade: 'B', credits: 3 });

    // Settings Modal State
    const [isSettingsOpen, setIsSettingsOpen] = useState(false);
    const [canvasConfig, setCanvasConfig] = useState({
        id: localStorage.getItem('CANVAS_ID') || 'self',
        token: localStorage.getItem('CANVAS_TOKEN') || '7~3LxQLMnxX4ZRzFteTC97YuyJuPaR92Aef88eLEB3M9YLtmXQ8ezH7TkPXDk4cYVx',
        lmsType: localStorage.getItem('LMS_TYPE') || 'Canvas'
    });

    useEffect(() => {
        fetchCourses();
        fetchUser();
    }, []);

    const calculateGPA = () => {
        const totalPoints = courses.reduce((acc, curr) => acc + (gradePoints[curr.grade] || 0) * curr.credits, 0);
        const totalCredits = courses.reduce((acc, curr) => acc + curr.credits, 0);
        return totalCredits ? (totalPoints / totalCredits).toFixed(2) : '0.00';
    };

    const fetchCourses = async () => {
        try {
            const res = await api.get('/api/courses');
            setCourses(res.data);
        } catch (error) {
            console.error("Failed to fetch courses", error);
        }
    };

    const fetchUser = async () => {
        try {
            const res = await api.get('/api/users/me');
            setUserData(res.data);
        } catch (error) {
            console.error("Failed to fetch user");
        }
    };

    const handleAdd = async (e) => {
        e.preventDefault();
        try {
            await api.post('/api/courses', newCourse);
            setNewCourse({ name: '', code: '', grade: 'B', credits: 3 });
            setIsAdding(false);
            fetchCourses();
            fetchUser(); // Refresh insight if it changed
        } catch (error) {
            alert("Failed to add course");
        }
    };

    const handleDelete = async (id) => {
        if (!window.confirm("Are you sure?")) return;
        try {
            await api.delete(`/api/courses/${id}`);
            fetchCourses();
            fetchUser();
        } catch (error) {
            alert("Failed to delete course");
        }
    };

    const handleSyncLMS = async () => {
        setIsSyncing(true);
        setSyncStatus(null);
        try {
            const res = await api.get('/api/lms/sync', {
                headers: {
                    'x-lms-type': canvasConfig.lmsType,
                    'x-lms-token': canvasConfig.token,
                    'x-lms-id': canvasConfig.id
                }
            });
            setSyncStatus({ success: true, message: res.data.message });
            fetchCourses();
            fetchUser(); // Get the new insight generated by backend
            // Clear status after 3 seconds
            setTimeout(() => setSyncStatus(null), 3000);
        } catch (error) {
            setSyncStatus({ success: false, message: `Failed to connect to ${canvasConfig.lmsType}.` });
            setTimeout(() => setSyncStatus(null), 3000);
        } finally {
            setIsSyncing(false);
        }
    };

    return (
        <div style={{ maxWidth: '1000px', margin: '0 auto' }}>

            {/* AI Insight Banner */}
            {userData?.ai_insight && (
                <motion.div
                    initial={{ y: -20, opacity: 0 }}
                    animate={{ y: 0, opacity: 1 }}
                    style={{
                        background: '#f0f9ff',
                        borderLeft: '4px solid #0ea5e9',
                        padding: '1.5rem',
                        borderRadius: '8px',
                        marginBottom: '2rem',
                        display: 'flex',
                        gap: '1rem',
                        alignItems: 'start'
                    }}
                >
                    <div style={{ background: '#0ea5e9', color: 'white', padding: '8px', borderRadius: '50%' }}>
                        <RefreshCw size={20} />
                    </div>
                    <div>
                        <h4 style={{ margin: '0 0 0.5rem 0', color: '#0369a1', fontSize: '1.1rem' }}>Artificial Intelligence Academic Insight</h4>
                        <p style={{ margin: 0, color: '#0c4a6e', lineHeight: '1.5' }}>
                            {userData.ai_insight}
                        </p>
                    </div>
                </motion.div>
            )}

            {/* Header Stats */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1.5rem', marginBottom: '2rem' }}>
                <motion.div initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} className="card-white" style={{ background: 'linear-gradient(135deg, #4f46e5, #6366f1)', color: 'white', border: 'none' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px' }}>
                        <div style={{ background: 'rgba(255,255,255,0.2)', padding: '8px', borderRadius: '8px' }}><Award size={20} /></div>
                        <span style={{ fontSize: '0.9rem', opacity: 0.9 }}>Cumulative GPA</span>
                    </div>
                    <div style={{ fontSize: '2.5rem', fontWeight: 'bold' }}>{calculateGPA()}</div>
                </motion.div>

                <motion.div initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.1 }} className="card-white">
                    <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px' }}>
                        <div style={{ background: '#ec489920', color: '#ec4899', padding: '8px', borderRadius: '8px' }}><BookOpen size={20} /></div>
                        <span style={{ fontSize: '0.9rem', color: '#64748b' }}>Active Courses</span>
                    </div>
                    <div style={{ fontSize: '2.5rem', fontWeight: 'bold' }}>{courses.length}</div>
                </motion.div>

                <motion.div initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.2 }} className="card-white">
                    <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px' }}>
                        <div style={{ background: '#10b98120', color: '#10b981', padding: '8px', borderRadius: '8px' }}><TrendingUp size={20} /></div>
                        <span style={{ fontSize: '0.9rem', color: '#64748b' }}>Total Credits</span>
                    </div>
                    <div style={{ fontSize: '2.5rem', fontWeight: 'bold' }}>{courses.reduce((acc, c) => acc + parseInt(c.credits || 0), 0)}</div>
                </motion.div>
            </div>

            {/* Course List Header */}
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
                <h2 style={{ fontSize: '1.5rem', fontWeight: '700' }}>My Courses</h2>
                <div style={{ display: 'flex', gap: '1rem' }}>
                    {syncStatus && (
                        <motion.div
                            initial={{ opacity: 0, x: 10 }}
                            animate={{ opacity: 1, x: 0 }}
                            style={{
                                display: 'flex',
                                alignItems: 'center',
                                gap: '8px',
                                fontSize: '0.85rem',
                                color: syncStatus.success ? '#10b981' : '#ef4444',
                                background: syncStatus.success ? '#dcfce7' : '#fee2e2',
                                padding: '4px 12px',
                                borderRadius: '20px',
                                fontWeight: '600'
                            }}
                        >
                            {syncStatus.message}
                        </motion.div>
                    )}

                    {/* LMS Selector */}
                    <select
                        value={canvasConfig.lmsType}
                        onChange={(e) => {
                            const newType = e.target.value;
                            setCanvasConfig(prev => ({ ...prev, lmsType: newType }));
                            localStorage.setItem('LMS_TYPE', newType);
                        }}
                        style={{
                            padding: '10px',
                            borderRadius: '8px',
                            border: '1px solid #e2e8f0',
                            background: 'white',
                            cursor: 'pointer',
                            fontWeight: '500',
                            color: '#475569'
                        }}
                    >
                        <option value="Canvas">Canvas</option>
                        <option value="Blackboard">Blackboard</option>
                        <option value="Brightspace">Brightspace</option>
                        <option value="Moodle">Moodle</option>
                    </select>

                    {/* Settings Button */}
                    <button
                        onClick={() => setIsSettingsOpen(true)}
                        style={{
                            background: 'white',
                            color: '#64748b',
                            border: '1px solid #e2e8f0',
                            padding: '10px',
                            borderRadius: '8px',
                            cursor: 'pointer',
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center'
                        }}
                        title="LMS Settings"
                    >
                        <Settings size={18} />
                    </button>

                    <button
                        onClick={handleSyncLMS}
                        disabled={isSyncing}
                        style={{
                            display: 'flex',
                            alignItems: 'center',
                            gap: '8px',
                            background: 'white',
                            color: '#4f46e5',
                            border: '1px solid #e2e8f0',
                            padding: '10px 20px',
                            borderRadius: '8px',
                            cursor: 'pointer',
                            fontWeight: '600',
                            transition: 'all 0.2s'
                        }}>
                        <RefreshCw size={18} className={isSyncing ? 'animate-spin' : ''} />
                        {isSyncing ? 'Syncing...' : `Sync ${canvasConfig.lmsType || 'Canvas'} Data`}
                    </button>
                    <button
                        onClick={() => setIsAdding(true)}
                        style={{ display: 'flex', alignItems: 'center', gap: '8px', background: '#4f46e5', color: 'white', border: 'none', padding: '10px 20px', borderRadius: '8px', cursor: 'pointer', fontWeight: '600' }}>
                        <Plus size={18} /> Add Course
                    </button>
                </div>
            </div>

            {/* Canvas Settings Modal */}
            {isSettingsOpen && (
                <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 }}>
                    <div className="card-white" style={{ width: '400px', padding: '2rem' }}>
                        <h3 style={{ marginTop: 0, marginBottom: '1.5rem', fontSize: '1.25rem' }}>{canvasConfig.lmsType} Configuration</h3>

                        <div style={{ marginBottom: '1rem' }}>
                            <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: '500', fontSize: '0.9rem' }}>{canvasConfig.lmsType} Student ID / User ID</label>
                            <input
                                type="text"
                                placeholder={`e.g. 12345`}
                                value={canvasConfig.id}
                                onChange={(e) => setCanvasConfig({ ...canvasConfig, id: e.target.value })}
                                style={{ width: '100%', padding: '10px', borderRadius: '8px', border: '1px solid #e2e8f0' }}
                            />
                        </div>

                        <div style={{ marginBottom: '1.5rem' }}>
                            <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: '500', fontSize: '0.9rem' }}>{canvasConfig.lmsType} API Token</label>
                            <input
                                type="password"
                                placeholder={`Enter your ${canvasConfig.lmsType} token`}
                                value={canvasConfig.token}
                                onChange={(e) => setCanvasConfig({ ...canvasConfig, token: e.target.value })}
                                style={{ width: '100%', padding: '10px', borderRadius: '8px', border: '1px solid #e2e8f0' }}
                            />
                            <div style={{ fontSize: '0.75rem', color: '#64748b', marginTop: '4px' }}>
                                This token is stored locally on your device.
                            </div>
                        </div>

                        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '10px' }}>
                            <button onClick={() => setIsSettingsOpen(false)} style={{ background: 'white', border: '1px solid #e2e8f0', padding: '8px 16px', borderRadius: '6px', cursor: 'pointer' }}>Cancel</button>
                            <button
                                onClick={() => {
                                    localStorage.setItem('CANVAS_ID', canvasConfig.id);
                                    localStorage.setItem('CANVAS_TOKEN', canvasConfig.token);
                                    localStorage.setItem('LMS_TYPE', canvasConfig.lmsType);
                                    setIsSettingsOpen(false);
                                    alert('Settings saved!');
                                }}
                                style={{ background: '#4f46e5', color: 'white', border: 'none', padding: '8px 16px', borderRadius: '6px', cursor: 'pointer' }}
                            >
                                Save Settings
                            </button>
                        </div>
                    </div>
                </div>
            )}

            <div className="card-white" style={{ padding: 0, overflow: 'hidden' }}>
                <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
                    <thead style={{ background: '#f8fafc', borderBottom: '1px solid #e2e8f0' }}>
                        <tr>
                            <th style={{ padding: '16px 24px', fontSize: '0.85rem', color: '#64748b', fontWeight: '600' }}>COURSE TITLE</th>
                            <th style={{ padding: '16px 24px', fontSize: '0.85rem', color: '#64748b', fontWeight: '600' }}>CREDITS</th>
                            <th style={{ padding: '16px 24px', fontSize: '0.85rem', color: '#64748b', fontWeight: '600' }}>GRADE</th>
                            {/* <th style={{ padding: '16px 24px', fontSize: '0.85rem', color: '#64748b', fontWeight: '600' }}>AI RECOMMENDATION</th> */}
                            <th style={{ padding: '16px 24px', fontSize: '0.85rem', color: '#64748b', fontWeight: '600', textAlign: 'right' }}>ACTIONS</th>
                        </tr>
                    </thead>
                    <tbody>
                        {courses.length === 0 ? (
                            <tr>
                                <td colSpan="5" style={{ padding: '3rem', textAlign: 'center', color: '#94a3b8' }}>
                                    No courses added yet. Click "Add Course" to get started.
                                </td>
                            </tr>
                        ) : (
                            courses.map((course, idx) => (
                                <tr key={course.id} style={{ borderBottom: idx !== courses.length - 1 ? '1px solid #f1f5f9' : 'none' }}>
                                    <td style={{ padding: '16px 24px' }}>
                                        <div style={{ fontWeight: '600' }}>{course.name}</div>
                                        <div style={{ fontSize: '0.8rem', color: '#64748b' }}>{course.code}</div>
                                    </td>
                                    <td style={{ padding: '16px 24px' }}>{course.credits}</td>
                                    <td style={{ padding: '16px 24px' }}>
                                        <span style={{
                                            padding: '4px 12px',
                                            borderRadius: '20px',
                                            fontSize: '0.9rem',
                                            fontWeight: '600',
                                            background: course.grade.startsWith('A') ? '#dcfce7' : course.grade.startsWith('B') ? '#dbeafe' : course.grade.startsWith('C') ? '#fef9c3' : '#fee2e2',
                                            color: course.grade.startsWith('A') ? '#166534' : course.grade.startsWith('B') ? '#1e40af' : course.grade.startsWith('C') ? '#854d0e' : '#991b1b',
                                        }}>
                                            {course.grade}
                                        </span>
                                    </td>
                                    {/* <td style={{ padding: '16px 24px', width: '35%' }}>
                                        {course.suggestion ? (
                                            <div style={{ padding: '8px 12px', background: '#f0f9ff', borderRadius: '8px', borderLeft: '3px solid #0ea5e9', fontSize: '0.85rem', color: '#0369a1', display: 'flex', gap: '8px' }}>
                                                <div style={{ flexShrink: 0 }}>💡</div>
                                                <div>{course.suggestion}</div>
                                            </div>
                                        ) : (
                                            <span style={{ color: '#cbd5e1', fontSize: '0.85rem' }}>No suggestions available</span>
                                        )}
                                    </td> */}
                                    <td style={{ padding: '16px 24px', textAlign: 'right' }}>
                                        <button onClick={() => handleDelete(course.id)} style={{ border: 'none', background: 'transparent', color: '#ef4444', cursor: 'pointer', padding: '8px' }}>
                                            <Trash2 size={18} />
                                        </button>
                                    </td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>

            {/* Add Course Modal Overlay */}
            {isAdding && (
                <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 100 }}>
                    <motion.div
                        initial={{ opacity: 0, scale: 0.9 }}
                        animate={{ opacity: 1, scale: 1 }}
                        className="card-white"
                        style={{ width: '100%', maxWidth: '500px', margin: '1rem' }}
                    >
                        <h3 style={{ fontSize: '1.25rem', fontWeight: '700', marginBottom: '1.5rem' }}>Add New Course</h3>
                        <form onSubmit={handleAdd} style={{ display: 'grid', gap: '1rem' }}>
                            <div>
                                <label style={{ display: 'block', fontSize: '0.9rem', fontWeight: '500', marginBottom: '4px' }}>Course Name</label>
                                <input
                                    required
                                    placeholder="e.g. Intro to Psychology"
                                    value={newCourse.name}
                                    onChange={e => setNewCourse({ ...newCourse, name: e.target.value })}
                                    style={{ width: '100%', padding: '10px', borderRadius: '8px', border: '1px solid #e2e8f0' }}
                                />
                            </div>
                            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                                <div>
                                    <label style={{ display: 'block', fontSize: '0.9rem', fontWeight: '500', marginBottom: '4px' }}>Course Code</label>
                                    <input
                                        required
                                        placeholder="PSY101"
                                        value={newCourse.code}
                                        onChange={e => setNewCourse({ ...newCourse, code: e.target.value })}
                                        style={{ width: '100%', padding: '10px', borderRadius: '8px', border: '1px solid #e2e8f0' }}
                                    />
                                </div>
                                <div>
                                    <label style={{ display: 'block', fontSize: '0.9rem', fontWeight: '500', marginBottom: '4px' }}>Credits</label>
                                    <input
                                        type="number"
                                        required
                                        min="1" max="6"
                                        value={newCourse.credits}
                                        onChange={e => setNewCourse({ ...newCourse, credits: parseInt(e.target.value) })}
                                        style={{ width: '100%', padding: '10px', borderRadius: '8px', border: '1px solid #e2e8f0' }}
                                    />
                                </div>
                            </div>
                            <div>
                                <label style={{ display: 'block', fontSize: '0.9rem', fontWeight: '500', marginBottom: '4px' }}>Current Grade</label>
                                <select
                                    value={newCourse.grade}
                                    onChange={e => setNewCourse({ ...newCourse, grade: e.target.value })}
                                    style={{ width: '100%', padding: '10px', borderRadius: '8px', border: '1px solid #e2e8f0', background: 'white' }}
                                >
                                    {Object.keys(gradePoints).map(g => <option key={g} value={g}>{g}</option>)}
                                </select>
                            </div>

                            <div style={{ display: 'flex', gap: '1rem', marginTop: '1rem' }}>
                                <button type="button" onClick={() => setIsAdding(false)} style={{ flex: 1, padding: '10px', background: 'white', border: '1px solid #e2e8f0', borderRadius: '8px', cursor: 'pointer' }}>Cancel</button>
                                <button type="submit" style={{ flex: 1, padding: '10px', background: '#4f46e5', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', fontWeight: '600' }}>Save Course</button>
                            </div>
                        </form>
                    </motion.div>
                </div>
            )}
        </div>
    );
};

export default Courses;
